version: "3"
services:
  postgres:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=helloworld
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helloworld
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  helloworld:
    image: "gcr.io/rvlt/helloworld:latest"
    container_name: "rvlt-helloworld"
    command: "/helloworld -db=postgres"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=helloworld
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helloworld
    ports:
      - "8080:8080"
